/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Administration.GestionJoueur;
import Forum.Forum;
import Forum.HistoriqueMessage;
import GestionJoueur.Gagnant;
import GestionJoueur.Joueur;
import GestionJoueur.Score;
import Vote.Elimination;
import Vote.GestionVotes;
import Vote.PhaseVote;
import Vote.Vote;
import java.util.ArrayList;

/**
 *
 * @author eyazi
 */
public class sixiemepage extends javax.swing.JFrame {
    private PhaseVote phaseVote;
    private GestionJoueur gestionJoueur;
    private int playersRemaining ;
    private ArrayList<String>votes;
    private HistoriqueMessage historiqueMessage;
    private Forum forum;
    private Score score;
    private Gagnant gagnant;
    private Elimination elimination;
    private GestionVotes gestionVote;
    private Joueur joueur1;
    /**
     * Creates new form sixiemepage
     */
    public sixiemepage(GestionJoueur gestionJoueur,Forum forum,HistoriqueMessage historiqueMessage)  {
        this.phaseVote = new PhaseVote();
        this.gestionJoueur= gestionJoueur;
        this.votes=new ArrayList<>();
        this.forum=forum;
        this.historiqueMessage=historiqueMessage;
        initComponents();
        initializePlayerCount() ;
    }
    private void initializePlayerCount() 
    {
    playersRemaining =  deuxiemePage.admin.getNombreJoueur();
    updatePlayerCounterDisplay();
    votes = new ArrayList<>();
    score=new Score();
    gagnant=new Gagnant();
    elimination=new Elimination();
    gestionVote=new GestionVotes();
    
    for (int i = 0; i < playersRemaining; i++) {
        votes.add(""); 
    }
    }
    private void updatePlayerCounterDisplay() {
    int currentIndex = deuxiemePage.admin.getNombreJoueur() - playersRemaining;
    if (currentIndex >= 0 && currentIndex < gestionJoueur.getListeJoueurs().size()) {
        jLabel7.setText(gestionJoueur.getListeJoueurs().get(currentIndex).getNom());
    } else {
        jLabel7.setText("Aucun joueur à afficher.");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(161, 175, 246));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("----  La session de vote ----");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("A qui vous voulez voter ?");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
            String vote = jTextField12.getText().trim();

    if (playersRemaining > 0 && !vote.isEmpty()) {
        int currentIndex = deuxiemePage.admin.getNombreJoueur() - playersRemaining;

        
        if (currentIndex < votes.size()) {
            votes.set(currentIndex, vote);
        } else {
            votes.add(vote);
        }

        System.out.println(vote + " est une personne ajoute a la vote");

        
        while (votes.size() > currentIndex + 1) {
            votes.remove(votes.size() - 1);
        }

        jTextField12.setText("");
        playersRemaining--;
        updatePlayerCounterDisplay();

        if (playersRemaining == 0) {
            
            jTextField12.setEnabled(false); // Désactive le champ de saisie.
        }
    }
    
     System.out.println( " fin de vote");
    Vote vote1 = new Vote();
    for (int i = 0; i < votes.size(); i++) {
        String nom = votes.get(i);
        Joueur joueurTrouve = vote1.trouverJoueurParNom(nom);

        if (joueurTrouve != null) {
            joueur1=joueurTrouve;
            joueurTrouve.setnombreDeVotesRecus();
            System.out.println("Le joueur " + joueurTrouve.getNom() + " a reçu un vote.");
        } else {
            System.out.println("Joueur non trouvé pour le nom : " + nom);
            // Vous pouvez ici afficher un message d'erreur ou demander une nouvelle saisie via l'interface.
        }
    }
        gestionVote.eliminerJoueurApresVote(gestionJoueur,phaseVote);
        System.out.println("\n\n La liste des Joueurs restants \n\n");
        gestionJoueur.AffichageListeJoueurs();
        
        if(joueur1.getRole().equalsIgnoreCase("Civile"))
        {
            septiemePage sept =new septiemePage(gestionJoueur,joueur1.getRole(),joueur1.getNom());
            sept.show();
            dispose();
        }
        else if(joueur1.getRole().equalsIgnoreCase("Undercover"))
        {
            septiemePage sept =new septiemePage(gestionJoueur,joueur1.getRole(),joueur1.getNom());
            sept.show();
            dispose();
        }
        else if(joueur1.getRole().equalsIgnoreCase("MrWhite"))
        {
            huitiemePage sept =new huitiemePage();
            sept.show();
            dispose();
        }
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sixiemepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sixiemepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sixiemepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sixiemepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables
}
